# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = 0

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/dotfiles/.vim/autoload/user/denite.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = 'source ~/dotfiles/.vim/autoload/user/deol.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/dotfiles/.vim/autoload/user/defx.vim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/dotfiles/.vim/autoload/user/vim-airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'edkolev/tmuxline.vim'
hook_add = 'source ~/dotfiles/.vim/autoload/user/tmuxline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/dotfiles/.vim/autoload/user/gitgutter.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = 'source ~/dotfiles/.vim/autoload/user/whitespace.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/dotfiles/.vim/autoload/user/quickrun.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/dotfiles/.vim/autoload/user/easymotion.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'source ~/dotfiles/.vim/autoload/user/vimproc.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = 'source ~/dotfiles/.vim/autoload/user/openbrowser.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'bfredl/nvim-miniyank'
hook_add = 'source ~/dotfiles/.vim/autoload/user/miniyank.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = 'source ~/dotfiles/.vim/autoload/user/vim-devicons.vim'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = 'source ~/dotfiles/.vim/autoload/user/sonictemplate.vim'

[[plugins]]
repo = 'basyura/Tweetvim'
hook_add = 'source ~/dotfiles/.vim/autoload/user/tweetvim.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'mattn/vim-starwars'

[[plugins]]
repo = 'willelz/badapple.nvim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'source ~/dotfiles/.vim/autoload/user/autosave.vim'

#[[plugins]]
#repo = 'neovim/nvim-lsp'
#hook_add = 'source ~/dotfiles/.vim/autoload/user/nvim-lsp.vim'

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#rev = 'next'
#build= 'bash install.sh'
#hook_add = 'source ~/dotfiles/.vim/autoload/user/languageclient-neovim.vim'

#[[plugins]]
#repo = 'itchyny/calendar.vim'

#[[plugins]]
#repo = 'thinca/vim-ref'
#hook_add = 'source ~/dotfiles/.vim/autoload/user/ref.vim'
#
#[[plugins]]
#repo = 'yuratomo/w3m.vim'
#hook_add = 'source ~/dotfiles/.vim/autoload/user/w3m.vim'
#
#[[plugins]]
#repo = 'koron/dicwin-vim'

