# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'call hyokoji#autosave#hook_add()'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call hyokoji#lightline#hook_add()'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'call hyokoji#gitgutter#hook_add()'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = 'call hyokoji#whitespace#hook_add()'

[[plugins]]
repo = 'KeitaNakamura/railscasts.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = 'call hyokoji#unite#hook_add()'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'call hyokoji#quickrun#hook_add()'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'call hyokoji#easymotion#hook_add()'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'call hyokoji#vimproc#hook_post_update()'

[[plugins]]
repo = 'twitvim/twitvim'
hook_add = 'call hyokoji#twitvim#hook_add()'

[[plugins]]
repo = 'Shougo/vimshell'
hook_add = 'call hyokoji#vimshell#hook_add()'

[[plugins]]
repo = 'kakkyz81/evervim'
hook_add = 'call hyokoji#evervim#hook_add()'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = 'call hyokoji#openbrowser#hook_add()'

[[plugins]]
repo = 'yaasita/edit-slack.vim'

[[plugins]]
repo = 'agatan/vim-vlack'

[[plugins]]
repo = 'tpope/vim-fugitive'
