# 遅延読み込み
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter' #インサートモードに入ったら読み込む
depends = ['deoplete-vim-lsp','vimtex'] #自分の関数が相手先の設定に使われているときに使う
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/deoplete.vim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_event = 'InsertEnter' #インサートモードに入ったら読み込む

#[[plugins]]
#repo = 'tbodt/deoplete-tabnine'
#on_ft = ['tex']
#build = 'bash install.sh'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_source = 'let g:markdown_syntax_conceal = 0'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['vim-markdown']

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_source = ['vim-markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = ['markdown','tex','gitcommit']

[[plugins]]
repo = 'lyuts/vim-rtags'
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/rtags.vim'
on_ft = ['c','cpp']

[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c','cpp']

[[plugins]]
repo = 'ncm2/float-preview.nvim'
on_if = 'has("nvim")'
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/float-preview.vim'

#[[plugins]]
#repo = 'Shougo/neco-vim'
#on_ft = ['vim']

#[[plugins]]
#repo = 'kakkyz81/evervim'
#on_if = 'has("python3")'
#hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/evervim.vim'

#[[plugins]]
#repo = 'w0rp/ale'
#hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/ale.vim'
#on_ft = ['c','cpp']

#[[plugins]]
#repo = 'Shougo/neco-syntax'
#on_event = 'InsertEnter'
#
#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#on_event = 'InsertEnter'
#depends = ['neosnippet-snippets']
#hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/neosnippet.vim'
#
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'
#on_event = 'InsertEnter'

[[plugins]]
repo  = 'lervag/vimtex'
on_ft = ['tex']
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/vimtex.vim'

