# 遅延読み込み
[[plugins]]
repo  = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1 #インサートモードに入ったら読み込む
depends = ['vimtex','neco-vim','neco-look']
hook_source = 'call hyokoji#neocomplete#hook_source()'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#on_i = 1 #インサートモードに入ったら読み込む
#depends = ['vimtex']
#hook_source = 'call hyokoji#deoplete#hook_source()'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_source = ['vim-markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Valloric/YouCompleteme'
on_ft = ['c','cpp']

[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = ['markdown','tex']

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
depends = ['neosnippet-snippets']
hook_source = 'call hyokoji#neosnippet#hook_source()'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']

