# 遅延読み込み
[[plugins]]
repo  = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1 #インサートモードに入ったら読み込む
depends = ['vimtex']
hook_source = 'call hyokoji#neocomplete#hook_source()'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_ft = ['markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Valloric/YouCompleteme'
on_ft = ['c','cpp']
on_i = 1
