# 遅延読み込み
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
nnoremap [denite] <Nop>
nmap <silent><space>d [denite]
"現在開いているファイルのディレクトリ下のファイル一覧。
nnoremap <silent> [denite]f :<C-u>Denite file<CR>
"バッファ一覧
nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
"レジスタ一覧
nnoremap <silent> [denite]r :<C-u>Denite register<CR>
"最近使用したファイル一覧
nnoremap <silent> [denite]m :<C-u>Denite file/old<CR>
'''
hook_source = 'source ~/dotfiles/.vim/autoload/user/denite.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = '''
nnoremap <silent><space>s :<C-u>Deol zsh -split=floating<CR>
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_add = '''
nnoremap <silent><space>f :<C-u>Defx -show-ignored-files -split=floating -winwidth=90 -direction=topleft -columns=mark:git:icons:filename:type:size:time<CR>
'''
hook_source = 'source ~/dotfiles/.vim/autoload/user/defx.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
on_event = ['InsertEnter','TextChanged']
hook_source = '''
let g:auto_save = 1  " デフォルトで有効にする
let g:auto_save_in_insert_mode = 0 "インサートモードのときは自動保存しない
let g:auto_save_silent = 1  " auto_saveの表示をしない
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = ['markdown','tex','gitcommit']

[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c','cpp']

[[plugins]]
repo  = 'lervag/vimtex'
on_ft = ['tex', 'markdown']
hook_source = '''
if has('mac') " この順番じゃないとうまくOS判定できない
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '@line @pdf @tex'
elseif has('unix')
let g:vimtex_view_general_viewer = 'evince'
endif
let g:vimtex_compiler_latexmk = {'callback' : 0}
let g:vimtex_compiler_progname = 'nvr'
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = ['neosnippet-snippets']
hook_source = '''
let g:neosnippet#snippets_directory="~/.vim/my_snippet"
let g:neosnippet#enable_conceal_markers=0
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
" Expand the completed snippet trigger by <CR>.
imap <expr><CR> (pumvisible() && neosnippet#expandable()) ? "\<Plug>(neosnippet_expand)" : "\<CR>"
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'Quickrun'
hook_source = 'source ~/dotfiles/.vim/autoload/user/quickrun.vim'

[[plugins]]
repo  = 'KeitaNakamura/tex-conceal.vim'
on_ft = 'tex'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install"'

