# 遅延読み込み
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter' #インサートモードに入ったら読み込む
depends = ['vimtex','deoplete-clang'] #自分の関数が相手先の設定に使われているときに使う
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/deoplete.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_source = ['deoplete.nvim']
hook_post_update = 'source ~/dotfiles/.vim/autoload/hyokoji/deoplete-tabnine.vim'

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c','cpp','cmake']
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/deoplete-clang.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertEnter'
depends = ['neosnippet-snippets']
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'

[[plugins]]
repo  = 'lervag/vimtex'
on_ft = ['tex']
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/vimtex.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_source = 'let g:markdown_syntax_conceal = 0'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['vim-markdown']

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_source = ['vim-markdown']

#toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = ['markdown','tex','vim','toml']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']

#[[plugins]]
#repo = 'Shougo/vimfiler'
#on_source = ['unite.vim']

[[plugins]]
repo = 'w0rp/ale'
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/ale.vim'
on_ft = ['c','cpp']

[[plugins]]
repo = 'lyuts/vim-rtags'
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/ale.vim'
on_ft = ['c','cpp']

[[plugins]]
repo = 'vim-scripts/a.vim'
hook_source = 'source ~/dotfiles/.vim/autoload/hyokoji/a.vim'
on_ft = ['c','cpp']

#[[plugins]]
#repo = 'critiqjo/lldb.nvim'
#on_ft = ['c','cpp']

