# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/autosave.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/gitgutter.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/whitespace.vim'

[[plugins]]
repo = 'KeitaNakamura/railscasts.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/denite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/quickrun.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/easymotion.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'source ~/dotfiles/.vim/autoload/hyokoji/vimproc.vim'

#[[plugins]]
#repo = 'kakkyz81/evervim'
#hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/evervim.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/openbrowser.vim'

#[[plugins]]
#repo = 'yaasita/edit-slack.vim'

#[[plugins]]
#repo = 'agatan/vim-vlack'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/defx.vim'

[[plugins]]
repo = 'basyura/twibill.vim'
#hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/defx.vim'

[[plugins]]
repo = 'basyura/Tweetvim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/tweetvim.vim'

[[plugins]]
repo = 'mattn/excitetranslate-vim'
#hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/tweetvim.vim'

[[plugins]]
repo = 'mattn/webapi-vim'
#hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/tweetvim.vim'

[[plugins]]
repo = 'koron/dicwin-vim'
#hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/tweetvim.vim'

[[plugins]]
repo = 'yuratomo/w3m.vim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/w3m.vim'

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/ref.vim'

