# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/deol.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/denite.vim'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = 'bash install.sh'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/autosave.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/vim-airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'edkolev/tmuxline.vim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/tmuxline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/gitgutter.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/whitespace.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/quickrun.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/easymotion.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'source ~/dotfiles/.vim/autoload/hyokoji/vimproc.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/openbrowser.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/defx.vim'

[[plugins]]
repo = 'koron/dicwin-vim'

[[plugins]]
repo = 'yuratomo/w3m.vim'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/w3m.vim'

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = 'source ~/dotfiles/.vim/autoload/hyokoji/ref.vim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'mattn/vim-starwars'

[[plugins]]
repo = 'willelz/badapple.nvim'

